application: blog-abhishek
version: live-v4
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on
- remote_api: on

libraries:
- name: django
  version: "latest"

- name: jinja2
  version: "2.6"

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /admin/pages/(.*)
  script: pages.app
  login: admin

- url: /admin/(.*)
  script: admin.app
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/(.*)

- url: /infopage/(.*)
  script: pages.app

- url: /google7d49977329ef01c9.html
  static_files: google7d49977329ef01c9.html
  upload: google7d49977329ef01c9.html

- url: /(.*)
  script: static.app
