application: blog-abhishek
version: live-v2
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on
- datastore_admin: on

handlers:
 
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
 
- url: /admin/pages/(.*)
  script: pages.py
  login: admin
  
- url: /admin/(.*)
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/(.*)

- url: /infopage/(.*)
  script: pages.py

- url: /google7d49977329ef01c9.html
  static_files: google7d49977329ef01c9.html
  upload: google7d49977329ef01c9.html

- url: /(.*)
  script: static.py
